CIS634/EasleyInventorySystem/EasleyInventorySystem/Controllers/InventoryManagerController.cs
using System;
using System.Collections.Generic;
using System.Data;
//using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using EasleyInventorySystem.Models;
using System.Web;

namespace EasleyInventorySystem.Controllers
{ 
    [Authorize] // Everybody past this point requires some level of authentication.
    public class InventoryManagerController : Controller
    {
        private InventoryDB db = new InventoryDB();
        private int PageSize = 10; //Define PageSize as a variable so we can customize it in web.config later

        //
        // GET: /InventoryManager/

        public ViewResult Index()
        {
            return View(db.Assets.ToList());
        }

        //
        // GET: /InventoryManager/Details/5

        [Authorize(Roles="Administrator,AssetAdmin,AssetViewer")]
        public ViewResult Details(Guid id)
        {
            Asset asset = db.Assets.Find(id);
            return View(asset);
        }

        //
        // GET: /InventoryManager/Create

        [Authorize(Roles="Administrator,AssetAdmin")]
        public ActionResult Create()
        {
            return View();
        } 

        //
        // POST: /InventoryManager/Create


        [Authorize(Roles = "Administrator,AssetAdmin")]
        [HttpPost]
        public ActionResult Create(Asset asset)
        {
            if (ModelState.IsValid)
            {
                asset.AssetID = Guid.NewGuid();
                asset.Purchase.TransactionID = Guid.NewGuid();
                db.Assets.Add(asset);
                //db.SaveChanges();
                db.SafeSave();
                return RedirectToAction("Index");  
            }

            return View(asset);
        }
        
        //
        // GET: /InventoryManager/Edit/5

        public ActionResult LocationSearch(string term)
        {
            var locations = GetLocations(term).Select(a => new { value = a.PurchaseLocation }).Distinct();
            return Json(locations, JsonRequestBehavior.AllowGet);
        }

        private List<Purchase> GetLocations(string searchTerm)
        {
            return db.Purchases.Where(a => a.PurchaseLocation.Contains(searchTerm)).ToList();
        }


        [Authorize(Roles = "Administrator,AssetAdmin")]
        public ActionResult Edit(Guid id)
        {
            Asset asset = db.Assets.Find(id);
            return View(asset);
        }

        //
        // POST: /InventoryManager/Edit/5

        [HttpPost]
        [Authorize(Roles = "Administrator,AssetAdmin")]
        public ActionResult Edit(Asset asset)
        {
            if (ModelState.IsValid)
            {
                db.Entry(asset).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(asset);
        }

        // GET: /InventoryManager/Search

        public ActionResult Search(string q)
        {
            //Decode "q"
            q = HttpUtility.UrlDecode(q);
            var assets = db.Assets.Include("Purchase")
                .Where(a => a.AssetName.Contains(q) || q==null || a.Purchase.PurchaseLocation.Contains(q))
                .Take(PageSize);

            return View(assets); //Call our view with the loaded asset page.
        }

        //
        // GET: /InventoryManager/Delete/5

        [Authorize(Roles = "Administrator,AssetAdmin")]
        public ActionResult Delete(Guid id)
        {
            Asset asset = db.Assets.Find(id);
            return View(asset);
        }

        //
        // POST: /InventoryManager/Delete/5

        [HttpPost, ActionName("Delete")]
        [Authorize(Roles = "Administrator,AssetAdmin")]
        public ActionResult DeleteConfirmed(Guid id)
        {            
            Asset asset = db.Assets.Find(id);
            db.Assets.Remove(asset);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            db.Dispose();
            base.Dispose(disposing);
        }
    }
}

CIS634/EasleyInventorySystem/EasleyInventorySystem/Views/InventoryManager/Create.cshtml
@model EasleyInventorySystem.Models.Asset

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>


@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>New Inventory Item</legend>

        <div class="editor-label">
            @Html.LabelFor(model => model.AssetName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AssetName)
            @Html.ValidationMessageFor(model => model.AssetName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageUrl)
        </div>
        <div class="editor-field">
            
            @Html.EditorFor(model => model.ImageUrl)
            @Html.ValidationMessageFor(model => model.ImageUrl)
        </div>


        <!-- Purchase.PurchaseLocation-->
        <div class="editor-label">
            @Html.LabelFor(model => model.Purchase.PurchaseLocation)
        </div>
        <div class="editor-field">
            <input type="text" name="Purchase.PurchaseLocation" data-autocomplete-source="@Url.Action("LocationSearch", "InventoryManager")" />



            <!-- Html.EditorFor(model => model.Purchase.PurchaseLocation) -->
            @Html.ValidationMessageFor(model => model.Purchase.PurchaseLocation)
        </div>

        
        <!-- Purchase.PurchaseDate-->
        <div class="editor-label">
            @Html.LabelFor(model => model.Purchase.PurchaseDate)
        </div>
        <div class="editor-field">
            <!-- Some jQuery UI for our date picker-->
            <script>
                $(function () {
                    $("#datepicker").datepicker(
                        {
                            changeMonth: true,
                            changeYear: true,
                            showButtonPanel: true,
                            numberOfMonths: 3,
                            showCurrentAtPos: 2,
                            dateFormat: "D, d MM, yy"
                        }
                        );
                });
            </script>
            <input type="text" name="Purchase.PurchaseDate" id="datepicker"  />

            <!-- @Html.EditorFor(model => model.Purchase.PurchaseDate) -->
            @Html.ValidationMessageFor(model => model.Purchase.PurchaseDate)
        </div>

        
        <!-- Purchase.PurchasePrice-->
        <div class="editor-label">
            @Html.LabelFor(model => model.Purchase.PurchasePrice)
        </div>
        <div class="editor-field">

            @Html.EditorFor(model => model.Purchase.PurchasePrice)
            @Html.ValidationMessageFor(model => model.Purchase.PurchasePrice)
        </div>


        


        <p>
            <input type="submit" value="Create" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

<!-- Connection AutoCompletes-->
<script>
    $("input[data-autocomplete-source]").each(function () {
        var target = $(this);
        target.autocomplete({ source: target.attr("data-autocomplete-source") });
    })
</script>


CIS634/EasleyInventorySystem/EasleyInventorySystem/Views/InventoryManager/Delete.cshtml
@model EasleyInventorySystem.Models.Asset

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<fieldset>
    <legend>Asset</legend>

    <div class="display-label">AssetName</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.AssetName)
    </div>

    <div class="display-label">ImageUrl</div>
    <div class="display-field">
        @Html.DisplayFor(model => model.ImageUrl)
    </div>
</fieldset>
@using (Html.BeginForm()) {
    <p>
        <input type="submit" value="Delete" /> |
        @Html.ActionLink("Back to List", "Index")
    </p>
}

CIS634/EasleyInventorySystem/EasleyInventorySystem/Views/InventoryManager/Details.cshtml
@model EasleyInventorySystem.Models.Asset

@{
    ViewBag.Title = "Details about";
}

<font size="5">@ViewBag.Title @Model.AssetName</font><br/>
<i>from @Model.Purchase.PurchaseLocation</i><br/>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm())
{
    @Html.ValidationSummary(true)
    <fieldset>
        
                    <!-- Fake Images provided by http://lorempixel.com-->
        <table>
            <tr>
                <td>@Html.Label("Asset Image")</td>
                <td><img src="@Model.ImageUrl" height="100" width="100" /></td>
            </tr>

            <tr>
                <td>Purchase Information</td>
                <td>
                    
                    @Html.ActionLink(@Model.Purchase.PurchaseLocation, "Search", "InventoryManager", new { q= Url.Encode(@Model.Purchase.PurchaseLocation) }, null)<br />
                    @Model.Purchase.PurchaseDate.ToString("D")<br />
                    @Model.Purchase.PurchasePrice.ToString("C")
                </td>
            </tr>
        </table>
                    

                        
                    
                  
                    

    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CIS634/EasleyInventorySystem/EasleyInventorySystem/Views/InventoryManager/Edit.cshtml
@model EasleyInventorySystem.Models.Asset

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<script src="@Url.Content("~/Scripts/jquery.validate.min.js")" type="text/javascript"></script>
<script src="@Url.Content("~/Scripts/jquery.validate.unobtrusive.min.js")" type="text/javascript"></script>

@using (Html.BeginForm()) {
    @Html.ValidationSummary(true)
    <fieldset>
        <legend>Asset</legend>

        @Html.HiddenFor(model => model.AssetID)

        <div class="editor-label">
            @Html.LabelFor(model => model.AssetName)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.AssetName)
            @Html.ValidationMessageFor(model => model.AssetName)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.ImageUrl)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.ImageUrl)
            @Html.ValidationMessageFor(model => model.ImageUrl)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Purchase.PurchaseLocation)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Purchase.PurchaseLocation)
            @Html.ValidationMessageFor(model => model.Purchase.PurchaseLocation)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Purchase.PurchasePrice)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Purchase.PurchasePrice)
            @Html.ValidationMessageFor(model => model.Purchase.PurchasePrice)
        </div>

        <div class="editor-label">
            @Html.LabelFor(model => model.Purchase.PurchaseDate)
        </div>
        <div class="editor-field">
            @Html.EditorFor(model => model.Purchase.PurchaseDate)
            @Html.ValidationMessageFor(model => model.Purchase.PurchaseDate)
        </div>

        <p>
            <input type="submit" value="Save" />
        </p>
    </fieldset>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

CIS634/EasleyInventorySystem/EasleyInventorySystem/Views/InventoryManager/Index.cshtml
@model IEnumerable<EasleyInventorySystem.Models.Asset>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<h3>Search:</h3>
@using (Html.BeginForm("Search", "InventoryManager", FormMethod.Get))
{
    <input type="text" name="q" />
    <input type="submit" value="Search" />

}


<p>
    @Html.ActionLink("Create New", "Create")
</p>
                      <table>
                          <tr>
                              <th></th>
                              <th>Picture</th>
                              <th>Asset Name</th>
                              <th>Purchase Date</th>
                              <th>Purchase Price</th>
                              <th>Purchase Location</th>
                          </tr>

                          @foreach (var a in Model)
                          {
                              
                              <tr>
                                  <td>
                                      @Html.ActionLink("Edit Record", "Edit", new { Id = @a.AssetID })<br /><br/>
                                  @Html.ActionLink("View Details", "Details", new { Id = @a.AssetID})
                                  </td>
                                  <!-- Fake Images provided by http://lorempixel.com-->
                                  <td>
                                      <div class="assetimage">
                                          <img src="@a.ImageUrl" height="100" width="100" />
                                      </div>
                                  </td>
                                  <td>@a.AssetName</td>
                                  <td>@a.Purchase.PurchaseDate.ToString("D")</td>
                                  <td>@a.Purchase.PurchasePrice.ToString("C")</td>
                                  <td>@Html.ActionLink(@a.Purchase.PurchaseLocation, "Search", "InventoryManager", new { q = Url.Encode(@a.Purchase.PurchaseLocation) }, null)</td>
                              </tr>
                          }
</table>

CIS634/EasleyInventorySystem/EasleyInventorySystem/Views/InventoryManager/Search.cshtml
@model IEnumerable<EasleyInventorySystem.Models.Asset>

@{
    ViewBag.Title = "Search";
    <h2>Results</h2>
    <table>
        <tr>
            <th></th>
            <th>Picture</th>
            <th>Asset Name</th>
            <th>Purchase Date</th>
            <th>Purchase Price</th>
            <th>Purchase Location</th>
        </tr>

    @foreach (var a in Model)
    {
        
        <tr>
            <td>
                @Html.ActionLink("Edit Record", "Edit", new { Id = @a.AssetID })<br /><br />
                @Html.ActionLink("View Details", "Details", new { Id = @a.AssetID })
            </td>
            <!-- Fake Images provided by http://lorempixel.com-->
            <td>
                <div class="assetimage">
                    <img src="@a.ImageUrl" height="100" width="100" />
                </div>
            </td>
            <td>@Html.ActionLink(@a.AssetName, "Details", new { id = a.AssetID })</td>
            <td>@a.Purchase.PurchaseDate.ToString("D")</td>
            <td>@a.Purchase.PurchasePrice.ToString("C")</td>
            <td>@a.Purchase.PurchaseLocation</td>
        </tr>
    }
    </table>
    
    <script>
        $(function () {
            $(".assetimage img").mouseover(function () {
                $(this).animate({ height: '+=25', width: '+=25' })
                       .animate({ height: '-=25', width: '-=25' });
            });
        });
    </script>
}

<h2>Search</h2>